[package]
name = "wasm-starter"
version = "0.1.0"
authors = ["Bridger Herman"]
edition = "2018"

[lib]
name = "wasm_starter"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.51"
wasm-logger = {git = "https://github.com/bridger-herman/wasm-logger.git"}
log = "0.4"
